// here we use open AI models which is generated by open AI. and we can just simply used for generate our result. models are train using
// deep learning, ML algorithm on very large dataSet. we select GPT-4o mini Model for our project . depending on user traffic in futrue
// we can also take premeum model .
// Tokens in open AI : Its a commen sequences of chars found in a set of text. (when we write one line model detect words on the basae of its style)

import express from "express";
import "dotenv/config";
import cors from "cors";
import mongoose from "mongoose";
import fetch from "node-fetch";
import passport from "passport";
import LocalStrategy from "passport-local";// local storage is only saficent for development state not production
import mongoStore from "connect-mongo"; // It store sesssion related info in production level. it is safe 
import User from "./models/User.js";
import session from "express-session";

import chatRoute from "./routes/chat.js";
import userRoute from "./routes/user.js";

const app = express();
const port = 8080;

app.use(express.json());
app.use(cors({
    origin: [
      "http://localhost:5173", "https://sigmagpt-sable.vercel.app/"
    ],
    credentials: true
}));

const store = mongoStore.create({ //in atlas database mongoStore create new collect called sessions for store session related info
  mongoUrl: process.env.MONGODB_URI,
  crypto: {
    secret: process.env.SECRET
  },
  touchAfter: 24 * 3600 //if there is no any changes in session (here do not interect with server). then we update our login or other info after 24h 
}); //if user does not perform any activity then user autometically logout

store.on("error", (err) => { // if store is fail to create mongoStore
  console.log("Error in mongoSession store : ", err);
});

app.set("trust proxy", 1);

const sessionOption = {
    store,
    secret: process.env.SECRET, //  change this in production
    resave: false,
    saveUninitialized: true,
    cookie: { // cookies for track the session . we have to login on web after 7 days
      expire: Date.now() + 7 * 24 * 60 * 60 * 1000,
      secure: true,
      sameSite: "none",
      maxAge:  7 * 24 * 60 * 60 * 1000, //7 day
      httpOnly: true // for prevent crose cripting attack
    }
};

app.use(session(sessionOption));

app.get("/", (req, res) => {
  res.send("Backend running");
});

//passpost Authentication
app.use(passport.initialize());
app.use(passport.session()); // all req of user assosiate by a single session of user
passport.use(new LocalStrategy(User.authenticate())); //all user is require to authenticate(login or signup) with LocalStrategy using 
//authenticate() (which is already create passpost)

passport.serializeUser(User.serializeUser()); //storing session info (login info)
passport.deserializeUser(User.deserializeUser());// remove session after expiry date

//all request
app.use("/api", chatRoute);
app.use("/api", userRoute);

app.set("trust proxy", 1);

// setInterval(() => {}, 1000);
const connectDb = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("connected with Database");
  } catch (err) {
    console.log("Database connection error : ", err);
  }
};

app.listen(port, () => {
  console.log("Server run on 8080"); // first we start server then we connect with our database
  connectDb();
});
